[package]
name = "pd-server"
version = "0.1.0"
authors = ["Ben Brunton <benbrunton@hotmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0"
log = "0.4.0"
env_logger = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
